# Generated by Django 4.0.5 on 2022-06-22 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('age', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='hobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hobby', models.CharField(max_length=50)),
                ('stuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sqlite3Exp.stuinfo')),
            ],
        ),
    ]
