# Generated by Django 4.0.5 on 2022-06-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite3Exp', '0003_rename_name_stuinfo_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuinfo',
            old_name='age',
            new_name='time',
        ),
    ]
