# Generated by Django 4.0.5 on 2022-06-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite3Exp', '0004_rename_age_stuinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuinfo',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
