# Generated by Django 4.0.5 on 2022-08-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlite3Exp', '0005_alter_stuinfo_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='hobby',
            new_name='Humi',
        ),
        migrations.RenameField(
            model_name='stuinfo',
            old_name='UID',
            new_name='Temp',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='stuid',
        ),
        migrations.AddField(
            model_name='hobby',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
